language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
os:
    - linux
    - osx
install:
    - python2 setup.py install
    - python3 setup.py install
script:
    - python2 example.py
    - python3 example.py
sudo: true
